---
  run_name: run1
  ########################
  # Entity-pairs processing parameters
  ########################
  # THe max char distance between 2 entities to consider relations
  max_dist: 256
  # Directory of annotations
  ann_dir: E:\David projects\ADE medication RE\data\ann
  # List of entity combos to include
  constrains: "[('Reason', 'Drug'),
                ('Drug', 'Route'),
                ('Drug', 'Strength'),
                ('Drug', 'Frequency'),
                ('Duration', 'Drug'),
                ('Drug', 'Form'),
                ('Drug', 'Dosage'),
                ('Drug', 'ADE')]"
  # Entity-pairs output directory
  entity_pairs_path: E:\David projects\ADE medication RE\Entity_pairs
  ########################
  # Model fine-tune parameters
  ########################
  # development set file path
  deve_id_file: E:\David projects\ADE medication RE\train_test_id\train_id
  # ratio of validation set. Will be sampled from development set
  valid_ratio: 0.2
  # Directory of text
  txt_dir: E:\David projects\ADE medication RE\data\text
  # Define relation labels and category numbers
  label_map: 
    No_relation : 0
    Reason-Drug : 1
    Route-Drug : 2
    Strength-Drug : 3
    Frequency-Drug : 4
    Duration-Drug : 5
    Form-Drug : 6
    Dosage-Drug : 7
    ADE-Drug : 8
  # tokenizer path
  tokenizer: E:\David projects\ADE medication RE\ClinicalBERT
  # Word tokens to be included in a segment
  word_token_length: 64
  # wordpiece tokens to include in a training instance
  wordpiece_token_length: 128
  # base NLP model file path
  base_model: E:\David projects\ADE medication RE\ClinicalBERT
  # learning rate
  lr: 2.e-6
  # n_ephoch
  n_epochs: 30
  # batch_size
  batch_size: 128
  # Output path
  out_path: E:\David projects\ADE medication RE
  ########################
  # Evaluation parameters
  ########################
  # test set file path
  test_id_file: E:\David projects\ADE medication RE\train_test_id\test_id
  # checkpoint path
  checkpoint_dir: E:\David projects\ADE medication RE\checkpoints\run1
  # checkpoint filename to evaluate, or "best" to pull the checkpoint with min validation loss.
  checkpoint: best
  ########################
  # Prediction parameters
  ########################
  # directory with documents to predict
  predict_doc_dir: E:\David projects\ADE medication NER\data\text
  # predict model
  predict_model: E:\David projects\ADE medication NER\Production Model
  # Output file
  predict_outfile: E:\David projects\ADE medication NER\prediction.pickle
  